### ISSUE TITLE
Bundle without Systemjs

### ISSUE THREAD

**Issue by blacksonic** [PointInside/ng2-toastr#10]
Searched but havent found js files without Systemjs, it really restricts the usage.
Are you planning to support AMD/Commonjs?

**Comment by derekshi** [comment]
Hi there, thanks for contacting. This is our side project. So unless it's starting to impact our own internal projects, we will update it. Otherwise, feel free to fork it and do the things you want :)

**Comment by leon** [comment]
I'm using webpack instead of system.js.

By changing the tsconfig.json to use `esm` instead of `system`
It would continue to work with system.js and also work with webpack.

https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md

@derekshi If I do a pull request for this, would you merge it?

**Comment by derekshi** [comment]
Yes, please create a pull request, @leon.

**Comment by brndusic** [comment]
@leon Can you please make a pull request with changes?

**Comment by leon** [comment]
The way that the repo is set up it would mean that we need to redo a lot.

There should be some best practices around how to build a community plugin. Maybe with the help of the new angular cli. 

I haven't had time to read up on how to do this yet. 

So there will not be a pull request yet :(

**Comment by aarnaud** [comment]
+1

**Comment by derekshi** [comment]
Close this because v0.3.0 above should be working with webpack build now.
