### ISSUE TITLE
Cannot find SourceMap 'ng2-tastr.js.map'

### ISSUE THREAD

**Issue by pearljamik** [PointInside/ng2-toastr#25]
I try to use ng2-toastr in the project. Unfortunately, when I start the application I get: 
Cannot find SourceMap 'ng2-tastr.js.map'

Why is that so , what is the workaround. I use webpack.

**Comment by bsanth** [comment]
We are using SystemJS and still I am hitting the same issue. Any ideas?

**Comment by ronzeidman** [comment]
The only thing that's needs to be done to fix this issue is to remove the last line `*.js.map` from .npmignore (https://github.com/PointInside/ng2-toastr/blob/master/.npmignore#L18) this will fix all bundling issues people have...

Anyway in the meantime after npm installing this I needed to manually remove the `//# sourceMappingURL=<filename>.js.map` from all files...
