### ISSUE TITLE
Working with Angular-cli

### ISSUE THREAD

**Issue by jculverwell** [PointInside/ng2-toastr#60]
Thought I'd add this in case anyone else bumps into this...

This projects works with Angular-CLI:

Follow the normal install instructions the then add the css to your angular-cli.json file like this:

```
  "styles": [
        "../node_modules/ng2-toastr/bundles/ng2-toastr.min.css"       
      ]
```

Do not add the js file to the scripts section as this will be automatically brought in via web pack as you have defined in in app.module.ts like this:

```
import {ToastModule} from 'ng2-toastr/ng2-toastr';
```

You may need to kill your console and do another ng-serve command for these changes to get picked up.

**Comment by derekshi** [comment]
Thanks @jculverwell

**Comment by jculverwell** [comment]
np, thank you for a great project!

**Comment by derekshi** [comment]
@jculverwell , do you mind adding this to README.md and send us a pull request? So that I can close this issue.

**Comment by fdcastel** [comment]
@derekshi: done in #68 by @samthomson 👍

**Comment by winnemucca** [comment]
Does this need to be added as **forRoot()?**

**Comment by derekshi** [comment]
`forRoot()` will give you default providers for `ToastsManager` and `ToastOptions`. Alternatively, you can add those providers on your own in `providers` list within your module.

**Comment by patryk-wlaz** [comment]
@fdcastel Where is this "done"? It is nowhere in the readme, and I just waisted some time trying to make styling work in my angular-cli project. Solution from @jculverwell works (thanks!)

Anyway - thanks for module :)

**Comment by fdcastel** [comment]
Hi @patryk-wlaz! I was referring to [this change in PR 68](https://github.com/PointInside/ng2-toastr/pull/68/files) made by samthomson (which added the information provided by jculverwell ).

Anyway, please consider that this was more than one year ago 😉 . The readme changed a lot since then.

**Comment by patryk-wlaz** [comment]
@fdcastel yes I'm referencing this exact line, and it is present in readme today - but it is about including `ng2-toastr.min.js` and this issue is about `ng2-toastr.min.css` :) 

So, in readme there IS information about how to include min.js in angular-cli projects, but there ISN'T any information about how to include min.css - other then basic instruction to include it in index.html or import into css, and it doesn't work (at least for me).

I think you should reopen this issue and some kind soul should consider creating pr adding @jculverwell solution to readme, right under lines about min.js that you referenced.

Yeah I know its an old issue but it is still relevant and I stepped on this today ;)
